language: python
os: linux
dist: xenial
python:
- 3.4
- 3.5
- 3.6
- 3.7
- 3.8

matrix:
  include:
  - dist: bionic
    python: 3.8
  - os: osx
    osx_image: xcode8.3
    language: generic
    python: 3.6
    before_install:
    - curl -Lo python.pkg https://www.python.org/ftp/python/3.6.8/python-3.6.8-macosx10.6.pkg
    - sudo installer -pkg python.pkg -target /
    - export PATH="$PATH:/Library/Frameworks/Python.framework/Versions/3.6/bin"
  - os: osx
    osx_image: xcode8.3
    language: generic
    python: 3.7
    before_install:
    - curl -Lo python.pkg https://www.python.org/ftp/python/3.7.5/python-3.7.5-macosx10.6.pkg
    - sudo installer -pkg python.pkg -target /
    - export PATH="$PATH:/Library/Frameworks/Python.framework/Versions/3.7/bin"
  - os: osx
    osx_image: xcode8.3
    language: generic
    python: 3.8
    before_install:
    - curl -Lo python.pkg https://www.python.org/ftp/python/3.8.0/python-3.8.0-macosx10.9.pkg
    - sudo installer -pkg python.pkg -target /
    - export PATH="$PATH:/Library/Frameworks/Python.framework/Versions/3.8/bin"
  - os: windows
    language: bash
    python: 3.8
    before_install:
    - choco install python sqlite
    - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
    - export PYTHON=$(which python)

script:
- ${PYTHON=python3} -m unittest -v sqlite3ct.test
- ${PYTHON=python3} -c 'from sqlite3ct import connect; connect(":memory:").execute("select json(1)")'
