trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

strategy:
  matrix:
    python34:
      python.version: '3.4'
    python35:
      python.version: '3.5'
    python36:
      python.version: '3.6'
    python37:
      python.version: '3.7'
    python38:
      python.version: '3.8'

pool:
  vmImage: "windows-2019"

steps:
- script: choco install sqlite
  displayName: 'install sqlite'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'
- script: python -m unittest -v sqlite3ct.test
  displayName: 'run test'
